-- Add new products missing from database
-- Generated: 2026-06-29

-- Human Hair With Small Curly Hair (wigs, +$40)
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('17d8a9f0-7845-46fa-9b9e-994e20896240', 'Human Hair With Small Curly Hair - 10 inch', '100% human hair curly wig with natural texture and bounce. Lightweight and breathable cap for all-day comfort.', 'wigs', 79.80, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image450.jpeg', 50, '', false, false, 'human_hair_small_curly', '10 inch');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('94301dff-dfa0-427f-9f4b-c5e8f37c66c7', 'Human Hair With Small Curly Hair - 12 inch', '100% human hair curly wig with natural texture and bounce. Lightweight and breathable cap for all-day comfort.', 'wigs', 80.80, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image450.jpeg', 50, '', false, false, 'human_hair_small_curly', '12 inch');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('ce1bd6fe-17ba-4484-b2f7-c74533225d5d', 'Human Hair With Small Curly Hair - 14 inch', '100% human hair curly wig with natural texture and bounce. Lightweight and breathable cap for all-day comfort.', 'wigs', 84.44, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image450.jpeg', 50, '', false, false, 'human_hair_small_curly', '14 inch');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('2b3a95e1-3a77-4637-be3c-17b114d680dc', 'Human Hair With Small Curly Hair - 16 inch', '100% human hair curly wig with natural texture and bounce. Lightweight and breathable cap for all-day comfort.', 'wigs', 90.08, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image450.jpeg', 50, '', false, false, 'human_hair_small_curly', '16 inch');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('504e6cb8-69e7-42bc-93ba-8a1f8d28b54b', 'Human Hair With Small Curly Hair - 18 inch', '100% human hair curly wig with natural texture and bounce. Lightweight and breathable cap for all-day comfort.', 'wigs', 100.36, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image450.jpeg', 50, '', false, false, 'human_hair_small_curly', '18 inch');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('4f9068a1-856f-4f83-84bf-dab24866738b', 'Human Hair With Small Curly Hair - 20 inch', '100% human hair curly wig with natural texture and bounce. Lightweight and breathable cap for all-day comfort.', 'wigs', 109.32, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image450.jpeg', 50, '', false, false, 'human_hair_small_curly', '20 inch');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('6c91fd5d-24df-4646-8113-dbb0008fb1cf', 'Human Hair With Small Curly Hair - 22 inch', '100% human hair curly wig with natural texture and bounce. Lightweight and breathable cap for all-day comfort.', 'wigs', 155.86, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image450.jpeg', 50, '', false, false, 'human_hair_small_curly', '22 inch');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('d819d6e5-0e7e-4a1f-b18c-bde1ded67447', 'Human Hair With Small Curly Hair - 8 inch', '100% human hair curly wig with natural texture and bounce. Lightweight and breathable cap for all-day comfort.', 'wigs', 78.97, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image450.jpeg', 50, '', false, false, 'human_hair_small_curly', '8 inch');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('f5c1626b-4d21-4e7c-9d02-f3650a738bf7', 'Human Hair With Small Curly Hair - 24 inch', '100% human hair curly wig with natural texture and bounce. Lightweight and breathable cap for all-day comfort.', 'wigs', 179.18, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image450.jpeg', 50, '', false, false, 'human_hair_small_curly', '24 inch');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('21e2d768-15e4-450d-9546-5228325457ea', 'Human Hair With Small Curly Hair - 26 inch', '100% human hair curly wig with natural texture and bounce. Lightweight and breathable cap for all-day comfort.', 'wigs', 198.96, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image450.jpeg', 50, '', false, false, 'human_hair_small_curly', '26 inch');

-- Large Capacity Travel Duffle Bag (accessories, +$3)
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('5a68d8b2-fd58-4fb2-b6c4-7a7e0ac4bd1d', 'Large Capacity Travel Duffle Bag - A Pink', 'Large capacity travel duffle bag with multiple compartments and durable zippers. Ideal for gym, travel, and weekend getaways.', 'accessories', 13.24, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image451.jpeg', 50, '', false, false, 'travel_duffle_bag', 'A Pink');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('0ccecec9-2bb0-4fae-87c0-089974201c3d', 'Large Capacity Travel Duffle Bag - B Sapphire Stripes', 'Large capacity travel duffle bag with multiple compartments and durable zippers. Ideal for gym, travel, and weekend getaways.', 'accessories', 13.87, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image451.jpeg', 50, '', false, false, 'travel_duffle_bag', 'B Sapphire Stripes');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('3a6509cd-150e-4904-b685-7b11e215a091', 'Large Capacity Travel Duffle Bag - Model B Black Stripes', 'Large capacity travel duffle bag with multiple compartments and durable zippers. Ideal for gym, travel, and weekend getaways.', 'accessories', 13.87, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image451.jpeg', 50, '', false, false, 'travel_duffle_bag', 'Model B Black Stripes');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('4ccee946-aefd-43c0-8a86-de8c4efd9860', 'Large Capacity Travel Duffle Bag - Beige', 'Large capacity travel duffle bag with multiple compartments and durable zippers. Ideal for gym, travel, and weekend getaways.', 'accessories', 13.24, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image451.jpeg', 50, '', false, false, 'travel_duffle_bag', 'Beige');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('10797e20-0b35-4954-ae89-c69eb18a23c7', 'Large Capacity Travel Duffle Bag - Black', 'Large capacity travel duffle bag with multiple compartments and durable zippers. Ideal for gym, travel, and weekend getaways.', 'accessories', 13.24, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image451.jpeg', 50, '', false, false, 'travel_duffle_bag', 'Black');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('a420debe-f524-439a-8c1b-8b1e9d5740be', 'Large Capacity Travel Duffle Bag - Blue', 'Large capacity travel duffle bag with multiple compartments and durable zippers. Ideal for gym, travel, and weekend getaways.', 'accessories', 20.91, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image451.jpeg', 50, '', false, false, 'travel_duffle_bag', 'Blue');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('9c8c248c-0049-46a2-97ea-6d978aaa6b60', 'Large Capacity Travel Duffle Bag - A Black', 'Large capacity travel duffle bag with multiple compartments and durable zippers. Ideal for gym, travel, and weekend getaways.', 'accessories', 19.42, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image451.jpeg', 50, '', false, false, 'travel_duffle_bag', 'A Black');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('a1c92681-be70-4c27-a152-3b49cafa7f47', 'Large Capacity Travel Duffle Bag - Set1', 'Large capacity travel duffle bag with multiple compartments and durable zippers. Ideal for gym, travel, and weekend getaways.', 'accessories', 23.48, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image451.jpeg', 50, '', false, false, 'travel_duffle_bag', 'Set1');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('ad90492a-ead3-41af-9e00-817532fe56e8', 'Large Capacity Travel Duffle Bag - Set 2', 'Large capacity travel duffle bag with multiple compartments and durable zippers. Ideal for gym, travel, and weekend getaways.', 'accessories', 23.48, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image451.jpeg', 50, '', false, false, 'travel_duffle_bag', 'Set 2');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('23f7e9d6-b758-470b-80c3-2351b7605ee3', 'Large Capacity Travel Duffle Bag - Set3', 'Large capacity travel duffle bag with multiple compartments and durable zippers. Ideal for gym, travel, and weekend getaways.', 'accessories', 23.48, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image451.jpeg', 50, '', false, false, 'travel_duffle_bag', 'Set3');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('9f9dd730-7bbb-495c-af7d-f0e43cafa90c', 'Large Capacity Travel Duffle Bag - Set4', 'Large capacity travel duffle bag with multiple compartments and durable zippers. Ideal for gym, travel, and weekend getaways.', 'accessories', 28.47, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image451.jpeg', 50, '', false, false, 'travel_duffle_bag', 'Set4');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('784e2ae6-002c-4b52-a17a-141612337b04', 'Large Capacity Travel Duffle Bag - Set5', 'Large capacity travel duffle bag with multiple compartments and durable zippers. Ideal for gym, travel, and weekend getaways.', 'accessories', 23.48, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image451.jpeg', 50, '', false, false, 'travel_duffle_bag', 'Set5');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('02401131-2735-42d2-971b-3e9f57db9353', 'Large Capacity Travel Duffle Bag - Set6', 'Large capacity travel duffle bag with multiple compartments and durable zippers. Ideal for gym, travel, and weekend getaways.', 'accessories', 23.48, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image451.jpeg', 50, '', false, false, 'travel_duffle_bag', 'Set6');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('a0ca1850-d1b4-4378-8021-24a653177d5c', 'Large Capacity Travel Duffle Bag - Set7', 'Large capacity travel duffle bag with multiple compartments and durable zippers. Ideal for gym, travel, and weekend getaways.', 'accessories', 23.48, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image451.jpeg', 50, '', false, false, 'travel_duffle_bag', 'Set7');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('737459f2-8347-4f9f-ac22-3fd81882173c', 'Large Capacity Travel Duffle Bag - Set8', 'Large capacity travel duffle bag with multiple compartments and durable zippers. Ideal for gym, travel, and weekend getaways.', 'accessories', 23.48, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image451.jpeg', 50, '', false, false, 'travel_duffle_bag', 'Set8');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('8b7223cb-1ed3-4619-a0f4-3daecc1cd4e1', 'Large Capacity Travel Duffle Bag - Set9', 'Large capacity travel duffle bag with multiple compartments and durable zippers. Ideal for gym, travel, and weekend getaways.', 'accessories', 23.48, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image451.jpeg', 50, '', false, false, 'travel_duffle_bag', 'Set9');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('c2805435-9731-4070-8894-1cd6bbe10a4a', 'Large Capacity Travel Duffle Bag - Set10', 'Large capacity travel duffle bag with multiple compartments and durable zippers. Ideal for gym, travel, and weekend getaways.', 'accessories', 23.48, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image451.jpeg', 50, '', false, false, 'travel_duffle_bag', 'Set10');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('ad07dc75-7734-400c-86fd-d480150798cc', 'Large Capacity Travel Duffle Bag - Set11', 'Large capacity travel duffle bag with multiple compartments and durable zippers. Ideal for gym, travel, and weekend getaways.', 'accessories', 33.72, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image451.jpeg', 50, '', false, false, 'travel_duffle_bag', 'Set11');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('a6e11afd-fa21-4e75-9628-37940d8078cd', 'Large Capacity Travel Duffle Bag - Set12', 'Large capacity travel duffle bag with multiple compartments and durable zippers. Ideal for gym, travel, and weekend getaways.', 'accessories', 33.72, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image451.jpeg', 50, '', false, false, 'travel_duffle_bag', 'Set12');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('5ce44c1b-f996-409e-8f56-39c458101ea3', 'Large Capacity Travel Duffle Bag - Set13', 'Large capacity travel duffle bag with multiple compartments and durable zippers. Ideal for gym, travel, and weekend getaways.', 'accessories', 33.72, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image451.jpeg', 50, '', false, false, 'travel_duffle_bag', 'Set13');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('2878e175-bbfb-4891-8ffe-c8ae5d45e2c1', 'Large Capacity Travel Duffle Bag - Set14', 'Large capacity travel duffle bag with multiple compartments and durable zippers. Ideal for gym, travel, and weekend getaways.', 'accessories', 33.72, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image451.jpeg', 50, '', false, false, 'travel_duffle_bag', 'Set14');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('78a17330-38a1-4b73-a4d4-b5d1c0fe2d4c', 'Large Capacity Travel Duffle Bag - Set15', 'Large capacity travel duffle bag with multiple compartments and durable zippers. Ideal for gym, travel, and weekend getaways.', 'accessories', 33.72, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image451.jpeg', 50, '', false, false, 'travel_duffle_bag', 'Set15');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('914c3c8e-3302-4446-a459-4a7eef74b104', 'Large Capacity Travel Duffle Bag - Set16', 'Large capacity travel duffle bag with multiple compartments and durable zippers. Ideal for gym, travel, and weekend getaways.', 'accessories', 33.72, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image451.jpeg', 50, '', false, false, 'travel_duffle_bag', 'Set16');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('63bad37f-246c-4974-9bd7-b3def6fbeff1', 'Large Capacity Travel Duffle Bag - Set17', 'Large capacity travel duffle bag with multiple compartments and durable zippers. Ideal for gym, travel, and weekend getaways.', 'accessories', 33.72, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image451.jpeg', 50, '', false, false, 'travel_duffle_bag', 'Set17');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('c9e28c0d-21da-4715-b500-bb22b1e50b33', 'Large Capacity Travel Duffle Bag - Set18', 'Large capacity travel duffle bag with multiple compartments and durable zippers. Ideal for gym, travel, and weekend getaways.', 'accessories', 33.72, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image451.jpeg', 50, '', false, false, 'travel_duffle_bag', 'Set18');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('4f5a261b-97bd-4c23-b9e6-06f174ed1e3b', 'Large Capacity Travel Duffle Bag - Set19', 'Large capacity travel duffle bag with multiple compartments and durable zippers. Ideal for gym, travel, and weekend getaways.', 'accessories', 33.72, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image451.jpeg', 50, '', false, false, 'travel_duffle_bag', 'Set19');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('23f5bb50-8c33-4c03-8f8f-72a7cc87a6d3', 'Large Capacity Travel Duffle Bag - Set21', 'Large capacity travel duffle bag with multiple compartments and durable zippers. Ideal for gym, travel, and weekend getaways.', 'accessories', 33.72, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image451.jpeg', 50, '', false, false, 'travel_duffle_bag', 'Set21');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('b7b8e4c7-22c3-4c6d-8320-d2474076175b', 'Large Capacity Travel Duffle Bag - Set22', 'Large capacity travel duffle bag with multiple compartments and durable zippers. Ideal for gym, travel, and weekend getaways.', 'accessories', 33.72, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image451.jpeg', 50, '', false, false, 'travel_duffle_bag', 'Set22');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('165f6042-6f5e-4932-a9e7-7cc6869f97db', 'Large Capacity Travel Duffle Bag - Set23', 'Large capacity travel duffle bag with multiple compartments and durable zippers. Ideal for gym, travel, and weekend getaways.', 'accessories', 33.72, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image451.jpeg', 50, '', false, false, 'travel_duffle_bag', 'Set23');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('2207e8a0-e53e-4974-9b10-0770e866be7f', 'Large Capacity Travel Duffle Bag - Set24', 'Large capacity travel duffle bag with multiple compartments and durable zippers. Ideal for gym, travel, and weekend getaways.', 'accessories', 33.72, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image451.jpeg', 50, '', false, false, 'travel_duffle_bag', 'Set24');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('8d851905-81e4-46f2-88a5-7549866d7dce', 'Large Capacity Travel Duffle Bag - Set25', 'Large capacity travel duffle bag with multiple compartments and durable zippers. Ideal for gym, travel, and weekend getaways.', 'accessories', 33.72, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image451.jpeg', 50, '', false, false, 'travel_duffle_bag', 'Set25');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('d1d3864a-39ff-4180-acf4-949729484c8b', 'Large Capacity Travel Duffle Bag - Set26', 'Large capacity travel duffle bag with multiple compartments and durable zippers. Ideal for gym, travel, and weekend getaways.', 'accessories', 33.72, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image451.jpeg', 50, '', false, false, 'travel_duffle_bag', 'Set26');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('881d3ae8-f377-4bec-919c-3b81d35d78a2', 'Large Capacity Travel Duffle Bag - Set27', 'Large capacity travel duffle bag with multiple compartments and durable zippers. Ideal for gym, travel, and weekend getaways.', 'accessories', 33.72, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image451.jpeg', 50, '', false, false, 'travel_duffle_bag', 'Set27');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('1abcaf18-5231-4795-9b04-ea3b1d040158', 'Large Capacity Travel Duffle Bag - Set28', 'Large capacity travel duffle bag with multiple compartments and durable zippers. Ideal for gym, travel, and weekend getaways.', 'accessories', 33.72, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image451.jpeg', 50, '', false, false, 'travel_duffle_bag', 'Set28');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('d98bcbe4-05e1-44fb-89e2-efa5a5873b51', 'Large Capacity Travel Duffle Bag - Set29', 'Large capacity travel duffle bag with multiple compartments and durable zippers. Ideal for gym, travel, and weekend getaways.', 'accessories', 33.72, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image451.jpeg', 50, '', false, false, 'travel_duffle_bag', 'Set29');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('902d909f-3f30-4535-b335-ae972e22fdd0', 'Large Capacity Travel Duffle Bag - Set30', 'Large capacity travel duffle bag with multiple compartments and durable zippers. Ideal for gym, travel, and weekend getaways.', 'accessories', 33.72, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image451.jpeg', 50, '', false, false, 'travel_duffle_bag', 'Set30');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('aca2c838-f67f-413e-9726-7437d0ce96e7', 'Large Capacity Travel Duffle Bag - Set31', 'Large capacity travel duffle bag with multiple compartments and durable zippers. Ideal for gym, travel, and weekend getaways.', 'accessories', 33.72, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image451.jpeg', 50, '', false, false, 'travel_duffle_bag', 'Set31');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('ec30fd31-5619-40fa-a8cd-4fd49488dafa', 'Large Capacity Travel Duffle Bag - Set32', 'Large capacity travel duffle bag with multiple compartments and durable zippers. Ideal for gym, travel, and weekend getaways.', 'accessories', 43.96, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image451.jpeg', 50, '', false, false, 'travel_duffle_bag', 'Set32');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('75cd7d46-2f1d-49af-8693-3fa4553527f6', 'Large Capacity Travel Duffle Bag - Set33', 'Large capacity travel duffle bag with multiple compartments and durable zippers. Ideal for gym, travel, and weekend getaways.', 'accessories', 23.48, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image451.jpeg', 50, '', false, false, 'travel_duffle_bag', 'Set33');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('22e6d585-5a42-4443-bede-5400f8fa65a1', 'Large Capacity Travel Duffle Bag - Set34', 'Large capacity travel duffle bag with multiple compartments and durable zippers. Ideal for gym, travel, and weekend getaways.', 'accessories', 82.68, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image451.jpeg', 50, '', false, false, 'travel_duffle_bag', 'Set34');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('4a859d00-84a2-4179-bffd-d23f5deb2505', 'Large Capacity Travel Duffle Bag - Set35', 'Large capacity travel duffle bag with multiple compartments and durable zippers. Ideal for gym, travel, and weekend getaways.', 'accessories', 16.20, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image451.jpeg', 50, '', false, false, 'travel_duffle_bag', 'Set35');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('16aa0e7d-5b1e-4537-9815-94ecce3a1cf5', 'Large Capacity Travel Duffle Bag - Set36', 'Large capacity travel duffle bag with multiple compartments and durable zippers. Ideal for gym, travel, and weekend getaways.', 'accessories', 16.20, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image451.jpeg', 50, '', false, false, 'travel_duffle_bag', 'Set36');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('cfe74950-1f6c-4b44-9886-1daf7747d991', 'Large Capacity Travel Duffle Bag - Set37', 'Large capacity travel duffle bag with multiple compartments and durable zippers. Ideal for gym, travel, and weekend getaways.', 'accessories', 16.20, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image451.jpeg', 50, '', false, false, 'travel_duffle_bag', 'Set37');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('edcb4a06-6257-45e9-9bed-0aa28896bcfc', 'Large Capacity Travel Duffle Bag - Set38', 'Large capacity travel duffle bag with multiple compartments and durable zippers. Ideal for gym, travel, and weekend getaways.', 'accessories', 16.20, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image451.jpeg', 50, '', false, false, 'travel_duffle_bag', 'Set38');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('b9e30f59-5b84-45fc-9859-1943acee0785', 'Large Capacity Travel Duffle Bag - Set39', 'Large capacity travel duffle bag with multiple compartments and durable zippers. Ideal for gym, travel, and weekend getaways.', 'accessories', 16.20, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image451.jpeg', 50, '', false, false, 'travel_duffle_bag', 'Set39');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('88580d82-32a3-42c2-bdb2-866a8a337a5e', 'Large Capacity Travel Duffle Bag - Set40', 'Large capacity travel duffle bag with multiple compartments and durable zippers. Ideal for gym, travel, and weekend getaways.', 'accessories', 43.96, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image451.jpeg', 50, '', false, false, 'travel_duffle_bag', 'Set40');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('fb497847-eefa-445e-8832-7db743f423b0', 'Large Capacity Travel Duffle Bag - Set41', 'Large capacity travel duffle bag with multiple compartments and durable zippers. Ideal for gym, travel, and weekend getaways.', 'accessories', 23.48, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image451.jpeg', 50, '', false, false, 'travel_duffle_bag', 'Set41');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('5cf7f086-9177-4b18-a794-749ca76bb15a', 'Large Capacity Travel Duffle Bag - A Black 2pcs', 'Large capacity travel duffle bag with multiple compartments and durable zippers. Ideal for gym, travel, and weekend getaways.', 'accessories', 35.84, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image451.jpeg', 50, '', false, false, 'travel_duffle_bag', 'A Black 2pcs');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('c8c8c14c-8dd5-420d-ad42-f672920e553c', 'Large Capacity Travel Duffle Bag - Set45', 'Large capacity travel duffle bag with multiple compartments and durable zippers. Ideal for gym, travel, and weekend getaways.', 'accessories', 29.66, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image451.jpeg', 50, '', false, false, 'travel_duffle_bag', 'Set45');

-- 7 Color LED Light Photon Face Mask (accessories, +$3)
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('be99b3e8-3181-40f3-9f66-62193814a61e', '7 Color LED Light Photon Face Mask - Neck Rejuvenation', '7-color LED light photon therapy face and neck mask for skin rejuvenation. Reduces fine lines and wrinkles for a youthful glow.', 'accessories', 22.96, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image453.jpeg', 50, '', false, false, NULL, NULL);

-- Phone Case Anti-peep (accessories, +$3)
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('d5637b49-1fb9-4e15-a387-3637e4023aaa', 'Phone Case Anti-peep - Black/iPhone8 7 plus', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 5.42, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Black/iPhone8 7 plus');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('b54fdd75-fe33-4a79-a590-8bcf106e26c8', 'Phone Case Anti-peep - Blue/iPhoneX', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 5.42, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Blue/iPhoneX');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('5fda3bdb-c6d6-4523-9a28-18582d499f56', 'Phone Case Anti-peep - Gold/IPhone6 plus', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 7.86, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Gold/IPhone6 plus');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('4c4b984f-eb15-4932-bea9-d1c5a9e845a0', 'Phone Case Anti-peep - Red/iPhone8 7', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 5.42, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Red/iPhone8 7');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('5afb86cf-549f-43b1-aaf9-ad03f803a528', 'Phone Case Anti-peep - Green/IPhone6', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 7.31, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Green/IPhone6');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('c3ddaeeb-b964-4c0a-9411-eae4b691bc99', 'Phone Case Anti-peep - Red/IPhone11pro', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 5.42, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Red/IPhone11pro');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('d2f68891-bb5c-4f78-a744-b59ef5d47993', 'Phone Case Anti-peep - Green/6S', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 7.51, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Green/6S');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('6ced47f0-8051-4d2f-8c4b-8893de1a3a08', 'Phone Case Anti-peep - Black/IPhone11pro', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 5.42, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Black/IPhone11pro');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('f8cfcc39-262e-4830-ab42-3a84f44f8a25', 'Phone Case Anti-peep - Blue/iPhone 12 Pro', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 5.42, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Blue/iPhone 12 Pro');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('45d6b0c3-cbde-46ba-9327-17ffa3d6b462', 'Phone Case Anti-peep - Black/Iphone 12 Pro Max', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 5.42, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Black/Iphone 12 Pro Max');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('3b469265-72f3-4262-adae-206f1b379597', 'Phone Case Anti-peep - Red/Iphone 12 Pro Max', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 5.42, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Red/Iphone 12 Pro Max');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('7243cf12-99be-4852-97cf-f34ef1d71746', 'Phone Case Anti-peep - Silver/Iphone 12 Pro Max', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 5.42, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Silver/Iphone 12 Pro Max');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('91f64109-24fa-4979-9594-57c64e49178e', 'Phone Case Anti-peep - Blue/Iphone 12 Pro Max', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 5.42, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Blue/Iphone 12 Pro Max');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('c1d4aecb-8270-4b18-b6bc-bc790e0720ce', 'Phone Case Anti-peep - Gold/Iphone 12 Pro Max', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 5.42, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Gold/Iphone 12 Pro Max');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('460d2673-0ac1-497d-ae76-c0009b301ae1', 'Phone Case Anti-peep - Green/Iphone 12 Pro Max', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 5.42, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Green/Iphone 12 Pro Max');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('f8898018-bc5d-4672-bc1f-aafc25ad2e0f', 'Phone Case Anti-peep - Black/Iphone 12 Pro', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 5.42, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Black/Iphone 12 Pro');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('aa026e6e-7001-410d-87cd-39aa1da6267f', 'Phone Case Anti-peep - Black/Iphone12 mini', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 7.45, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Black/Iphone12 mini');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('1add2239-9e41-4664-86ff-2862f28ea7bc', 'Phone Case Anti-peep - Red/Iphone12 mini', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 7.45, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Red/Iphone12 mini');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('ca8018fb-a900-443f-81e8-0a00492f619f', 'Phone Case Anti-peep - Silver/Iphone12 mini', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 7.45, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Silver/Iphone12 mini');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('72ea1d5d-a382-4b2a-9c8e-746925e692a1', 'Phone Case Anti-peep - Blue/Iphone12 mini', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 7.45, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Blue/Iphone12 mini');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('9c1e1f8c-5da0-4d5a-9913-90def16aa709', 'Phone Case Anti-peep - Gold/Iphone12 mini', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 7.45, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Gold/Iphone12 mini');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('1479ec96-16fc-4660-ab31-c2ed38e375a8', 'Phone Case Anti-peep - Green/Iphone12 mini', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 7.45, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Green/Iphone12 mini');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('b879b1de-825a-4abc-bb9b-17582189347f', 'Phone Case Anti-peep - Black/IPhone12', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 5.42, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Black/IPhone12');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('0ad841bc-3e38-46d4-9b4a-55be605caa48', 'Phone Case Anti-peep - Silver/IPhone XS', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 5.42, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Silver/IPhone XS');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('332c5d44-0cb9-4411-9de7-b43d48690cbd', 'Phone Case Anti-peep - Blue/SE 2020', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 7.04, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Blue/SE 2020');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('cbf24a00-4aff-4a82-8711-27d67e8e4be8', 'Phone Case Anti-peep - Silver/iPhoneX', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 5.42, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Silver/iPhoneX');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('3cc0f526-a2a5-41ab-ba3f-21854ea5b2f8', 'Phone Case Anti-peep - Black/iPhone8 7', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 5.42, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Black/iPhone8 7');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('a253b9ec-4bfe-4817-80af-d6e8bc911003', 'Phone Case Anti-peep - Gold/6S', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 7.51, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Gold/6S');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('cbfd140e-6437-4dae-a1e2-c19efacdb39f', 'Phone Case Anti-peep - Red/SE 2020', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 7.17, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Red/SE 2020');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('a1172279-424c-4074-b44c-29cb31ce4fbc', 'Phone Case Anti-peep - Red/iPhoneX', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 5.42, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Red/iPhoneX');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('3085435d-e9b0-46bc-ac24-c38222880666', 'Phone Case Anti-peep - Gold/IPhone11pro', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 5.42, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Gold/IPhone11pro');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('a3c32418-0ef2-4f9a-b8da-172b2ca7de31', 'Phone Case Anti-peep - Black/SE 2020', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 7.04, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Black/SE 2020');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('1b5881ae-469f-44bc-af5f-b033fd3900d7', 'Phone Case Anti-peep - Blue/6S', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 7.51, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Blue/6S');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('c1400c79-a012-40be-9c6f-10510e3e4e2a', 'Phone Case Anti-peep - Green/iPhone8 7', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 5.42, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Green/iPhone8 7');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('9b3bc991-cb37-4dd0-bd10-7bb0add80ce8', 'Phone Case Anti-peep - Gold/SE 2020', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 7.04, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Gold/SE 2020');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('7b880468-f4c6-40e2-bad1-4950478543f8', 'Phone Case Anti-peep - Silver/SE 2020', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 7.04, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Silver/SE 2020');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('c65b59f7-c38a-4426-b63a-8f7ccdaa8334', 'Phone Case Anti-peep - Silver/Iphone 11pro max', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 5.42, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Silver/Iphone 11pro max');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('26cfba86-9f6b-4523-aac1-bce99a999a40', 'Phone Case Anti-peep - Black/IPhone XS', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 5.42, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Black/IPhone XS');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('382001a8-0aa7-4dfc-a64b-d1aa1da7d181', 'Phone Case Anti-peep - Red/IPhone XS MAX', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 5.42, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Red/IPhone XS MAX');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('8a7d5e21-8e29-49c5-baaa-af795cfe74e8', 'Phone Case Anti-peep - Silver/IPhone11', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 5.42, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Silver/IPhone11');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('28419902-a7ce-454a-bd68-3d5bbb595143', 'Phone Case Anti-peep - Silver/IPhone XS MAX', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 5.42, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Silver/IPhone XS MAX');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('845b0dfe-c58b-4dce-992b-8c86f78f4562', 'Phone Case Anti-peep - Red/iPhone8 7 plus', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 5.42, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Red/iPhone8 7 plus');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('65b92b7e-3ffd-4ef1-a6ca-04017762398d', 'Phone Case Anti-peep - Green/IPhone XS MAX', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 5.42, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Green/IPhone XS MAX');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('f45649f9-5e5c-44c1-84dd-f67b28aa839b', 'Phone Case Anti-peep - Silver/IPhone6', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 7.37, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Silver/IPhone6');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('85df4c08-92ef-41c7-b2dd-155ffbd649c4', 'Phone Case Anti-peep - Silver/IPhoneXR', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 5.42, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Silver/IPhoneXR');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('19d1601c-8ff5-41cd-9dc7-e7f53dbf90b4', 'Phone Case Anti-peep - Silver/6S', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 7.51, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Silver/6S');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('ef1f99c9-fec0-41ce-b71d-3395bcb37a24', 'Phone Case Anti-peep - Green/iPhone8 7 plus', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 5.42, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Green/iPhone8 7 plus');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('71ece00c-c5ec-4b67-9f60-d58b298a6005', 'Phone Case Anti-peep - Black/iPhoneX', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 5.42, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Black/iPhoneX');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('ac3079b4-7433-4c0f-b4bb-5f31e05de572', 'Phone Case Anti-peep - Silver/IPhone6 plus', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 7.86, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Silver/IPhone6 plus');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('495f47b2-39d7-4f56-aecc-cdfa29d0c6d1', 'Phone Case Anti-peep - Green/iPhoneX', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 5.42, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Green/iPhoneX');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('0a403f88-9a23-410e-b1b5-c0d738056c32', 'Phone Case Anti-peep - Blue/Iphone 11pro max', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 5.42, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Blue/Iphone 11pro max');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('d14bb7e8-3ab4-46f9-abe0-319d9c50d500', 'Phone Case Anti-peep - Black/IPhone XS MAX', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 5.42, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Black/IPhone XS MAX');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('a6c55e9c-5973-49c4-aff0-7e4da62f01a2', 'Phone Case Anti-peep - Silver/iPhone8 7', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 5.42, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Silver/iPhone8 7');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('69b087cb-5b69-432c-b89a-df52f19ab6ff', 'Phone Case Anti-peep - Gold/iPhoneX', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 5.42, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Gold/iPhoneX');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('0a2bc50d-2178-4531-831c-a3c15bb19ed6', 'Phone Case Anti-peep - Red/IPhoneXR', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 5.42, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Red/IPhoneXR');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('531401a4-3af7-4336-9ef2-0b56638fd8ee', 'Phone Case Anti-peep - Silver/iPhone8 7 plus', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 5.42, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Silver/iPhone8 7 plus');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('aa856c62-1d2a-48ed-9da0-af8059a15eba', 'Phone Case Anti-peep - Black/IPhoneXR', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 5.42, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Black/IPhoneXR');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('7820a680-ba32-4dc9-a60c-e442bd59d36a', 'Phone Case Anti-peep - Black/6S', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 7.51, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Black/6S');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('df5f1a27-3943-41d1-b015-3b8ac3448825', 'Phone Case Anti-peep - Blue/IPhoneXR', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 5.42, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Blue/IPhoneXR');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('a0e4db76-0ebd-42e5-bd68-920975e08011', 'Phone Case Anti-peep - Green/SE 2020', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 7.04, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Green/SE 2020');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('34069cba-13f4-4153-99e7-41bf531706b7', 'Phone Case Anti-peep - Blue/IPhone11', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 5.42, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Blue/IPhone11');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('d3903762-365a-47b7-a5c8-b80c354c1e6e', 'Phone Case Anti-peep - Red/IPhone6 plus', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 7.86, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Red/IPhone6 plus');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('399609d1-5209-4724-a48b-4daca0fe9eb9', 'Phone Case Anti-peep - Red/Iphone 11pro max', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 5.42, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Red/Iphone 11pro max');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('8b625435-827c-4ebf-a88a-9012571155e8', 'Phone Case Anti-peep - Green/Iphone 11pro max', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 5.42, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Green/Iphone 11pro max');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('e4e324ea-78e6-497a-a029-263132f8ab91', 'Phone Case Anti-peep - Red/6S', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 7.37, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Red/6S');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('7bdf3370-2b72-442d-ae6d-22d7afb8e107', 'Phone Case Anti-peep - Gold/iPhone8 7', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 5.42, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Gold/iPhone8 7');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('5898509a-5e50-41f1-a4d5-5310e4a95aef', 'Phone Case Anti-peep - Gold/IPhoneXR', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 5.42, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Gold/IPhoneXR');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('b6e0bfd5-b90a-4233-bd2f-f1423dfd8660', 'Phone Case Anti-peep - Green/IPhone11pro', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 5.42, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Green/IPhone11pro');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('91d9c5e3-0fa7-4448-912a-69bdee4c211d', 'Phone Case Anti-peep - Green/IPhone XS', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 5.42, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Green/IPhone XS');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('0345b8fe-037b-46c3-b95b-c1148e060d7d', 'Phone Case Anti-peep - Red/IPhone11', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 5.42, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Red/IPhone11');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('65b26ea6-3b95-443e-b7e5-5ec81ee2c875', 'Phone Case Anti-peep - Red/IPhone XS', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 5.42, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Red/IPhone XS');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('5a6d5770-f547-462f-8c2c-3ba5b74ea913', 'Phone Case Anti-peep - Black/IPhone6 plus', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 7.86, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Black/IPhone6 plus');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('2376d102-6e02-4281-a3c3-3a2714ae7a88', 'Phone Case Anti-peep - Gold/IPhone6', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 7.37, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Gold/IPhone6');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('3f0aabee-fcc8-474d-b7df-9f0a5f8f1e3e', 'Phone Case Anti-peep - Blue/IPhone XS', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 5.42, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Blue/IPhone XS');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('52a627b9-e395-4fe2-a936-a9d1435d09e1', 'Phone Case Anti-peep - Blue/IPhone11pro', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 5.42, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Blue/IPhone11pro');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('2f9d2693-8bc6-4b7b-b3eb-534a23b5a6a1', 'Phone Case Anti-peep - Silver/Iphone11pro', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 5.42, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Silver/Iphone11pro');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('95abc098-e07d-4ff7-ac5a-63e96af33d7a', 'Phone Case Anti-peep - Gold/IPhone XS', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 5.42, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Gold/IPhone XS');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('9329cd5b-50fd-496b-9f1f-f39c4d6c3ef6', 'Phone Case Anti-peep - Green/IPhoneXR', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 5.42, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Green/IPhoneXR');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('59a67d10-bae3-4a0f-b9e1-dbe7feedcd15', 'Phone Case Anti-peep - Blue/IPhone6', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 7.37, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Blue/IPhone6');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('fa42f21e-a419-4108-b398-bb2a6a9de6a5', 'Phone Case Anti-peep - Blue/IPhone XS MAX', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 5.42, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Blue/IPhone XS MAX');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('2f8fe4d3-62fb-4d2f-b185-c22c2d19ac33', 'Phone Case Anti-peep - Green/IPhone6 plus', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 7.86, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Green/IPhone6 plus');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('437eb65f-ad78-415a-ac05-9a5661a289f7', 'Phone Case Anti-peep - Black/Iphone 11pro max', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 5.42, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Black/Iphone 11pro max');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('17c4f9ef-ba31-417b-8044-dcbf6607f7df', 'Phone Case Anti-peep - Black/IPhone6', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 7.37, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Black/IPhone6');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('4d152289-a390-4ad3-9027-a1648ed112f4', 'Phone Case Anti-peep - Red/IPhone6', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 7.37, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Red/IPhone6');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('3e4ea3a0-a4a3-40df-af80-6f257dc6d92b', 'Phone Case Anti-peep - Gold/Iphone 11pro max', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 5.42, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Gold/Iphone 11pro max');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('75db3c2e-1699-4695-85a0-2a2453e081a0', 'Phone Case Anti-peep - Gold/iPhone8 7 plus', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 5.42, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Gold/iPhone8 7 plus');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('ff9bfa10-88d2-4732-8230-baed8915f3fd', 'Phone Case Anti-peep - Gold/IPhone XS MAX', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 5.42, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Gold/IPhone XS MAX');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('619ea552-4ccc-4224-8997-f17c537e4417', 'Phone Case Anti-peep - Green/IPhone11', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 5.42, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Green/IPhone11');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('c927c2eb-ec3b-4309-853a-f3024119f209', 'Phone Case Anti-peep - Blue/iPhone8 7', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 5.42, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Blue/iPhone8 7');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('15f8ab54-dca5-4146-89d3-005c41d15417', 'Phone Case Anti-peep - Blue/iPhone8 7 plus', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 5.42, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Blue/iPhone8 7 plus');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('d3632bf2-7d10-4d56-b824-dfe9c314c054', 'Phone Case Anti-peep - Black/IPhone11', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 5.42, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Black/IPhone11');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('2c86ab7c-8da8-4b6f-9d41-658c6e1efa49', 'Phone Case Anti-peep - Blue/IPhone6 plus', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 7.86, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Blue/IPhone6 plus');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('ae4dc293-dcbf-457a-899c-90f9cba6e856', 'Phone Case Anti-peep - Gold/IPhone11', 'Magnetic privacy phone case with tempered glass protection. Anti-peep technology prevents side-angle screen viewing for enhanced privacy.', 'accessories', 5.42, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image452.jpeg', 50, '', false, false, 'phone_case_anti_peep', 'Gold/IPhone11');

-- Manicure Accessories A010 (nails, +$12)
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('2ddd2a42-324f-4076-be03-aea029694f1b', 'Manicure Accessories - A010', 'Professional nail art accessory set A010 with essential tools for creating beautiful nail designs at home or salon.', 'nails', 12.49, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image454.jpeg', 50, '', false, false, NULL, 'A010');
