-- Add batch 3 products missing from database
-- Generated: 2026-06-29

-- Solar Charging Fan Hat (accessories, +$3)
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('be894e1c-4463-459b-83d1-9ea47fdc1b1f', 'Solar Charging Fan Hat - Dark Gray/4to8 Hours', 'Solar-powered fan baseball cap with breathable mesh design. UV protection with sustainable fan use for outdoor sun protection.', 'accessories', 10.46, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image455.webp', 50, '', false, false, 'solar_fan_hat', 'Dark Gray/4to8 Hours');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('812e0bc8-5aac-47ac-b6c2-9c5f607752a5', 'Solar Charging Fan Hat - Dark Gray/8to16 Hours', 'Solar-powered fan baseball cap with breathable mesh design. UV protection with sustainable fan use for outdoor sun protection.', 'accessories', 12.12, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image455.webp', 50, '', false, false, 'solar_fan_hat', 'Dark Gray/8to16 Hours');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('23f5aba5-4711-4ab7-bd81-e69ae0e1ea75', 'Solar Charging Fan Hat - Light Gray/4to8 Hours', 'Solar-powered fan baseball cap with breathable mesh design. UV protection with sustainable fan use for outdoor sun protection.', 'accessories', 10.46, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image455.webp', 50, '', false, false, 'solar_fan_hat', 'Light Gray/4to8 Hours');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('72642ac8-7e32-408a-8281-ce3bb6006c6a', 'Solar Charging Fan Hat - Light Gray/8to16 Hours', 'Solar-powered fan baseball cap with breathable mesh design. UV protection with sustainable fan use for outdoor sun protection.', 'accessories', 12.12, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image455.webp', 50, '', false, false, 'solar_fan_hat', 'Light Gray/8to16 Hours');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('819bcbc2-7a8c-47ff-a9f6-10f04c4c978c', 'Solar Charging Fan Hat - Black/4to8 Hours', 'Solar-powered fan baseball cap with breathable mesh design. UV protection with sustainable fan use for outdoor sun protection.', 'accessories', 10.46, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image455.webp', 50, '', false, false, 'solar_fan_hat', 'Black/4to8 Hours');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('f8d121db-9ef8-4e6e-b118-aca55e62192e', 'Solar Charging Fan Hat - Black/8to16 Hours', 'Solar-powered fan baseball cap with breathable mesh design. UV protection with sustainable fan use for outdoor sun protection.', 'accessories', 12.12, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image455.webp', 50, '', false, false, 'solar_fan_hat', 'Black/8to16 Hours');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('e9e0ec25-557e-4e75-a00b-0314ae02ae0b', 'Solar Charging Fan Hat - Navy Blue/4to8 Hours', 'Solar-powered fan baseball cap with breathable mesh design. UV protection with sustainable fan use for outdoor sun protection.', 'accessories', 10.46, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image455.webp', 50, '', false, false, 'solar_fan_hat', 'Navy Blue/4to8 Hours');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('c7b9094d-d101-455e-90c5-add43d92f671', 'Solar Charging Fan Hat - Navy Blue/8to16 Hours', 'Solar-powered fan baseball cap with breathable mesh design. UV protection with sustainable fan use for outdoor sun protection.', 'accessories', 12.12, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image455.webp', 50, '', false, false, 'solar_fan_hat', 'Navy Blue/8to16 Hours');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('d8694d70-2b17-4d94-801f-b1a3c91f48b5', 'Solar Charging Fan Hat - Beige/4to8 Hours', 'Solar-powered fan baseball cap with breathable mesh design. UV protection with sustainable fan use for outdoor sun protection.', 'accessories', 10.46, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image455.webp', 50, '', false, false, 'solar_fan_hat', 'Beige/4to8 Hours');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('aac4b345-8f87-41cd-b6e1-5849abcd73a0', 'Solar Charging Fan Hat - Beige/8to16 Hours', 'Solar-powered fan baseball cap with breathable mesh design. UV protection with sustainable fan use for outdoor sun protection.', 'accessories', 12.12, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image455.webp', 50, '', false, false, 'solar_fan_hat', 'Beige/8to16 Hours');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('0e4e0669-f530-4573-a5bc-a111dfe11ccb', 'Solar Charging Fan Hat - White/4to8 Hours', 'Solar-powered fan baseball cap with breathable mesh design. UV protection with sustainable fan use for outdoor sun protection.', 'accessories', 10.46, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image455.webp', 50, '', false, false, 'solar_fan_hat', 'White/4to8 Hours');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('5e3edc32-bfe4-4141-b599-faa07a4d223a', 'Solar Charging Fan Hat - White/8to16 Hours', 'Solar-powered fan baseball cap with breathable mesh design. UV protection with sustainable fan use for outdoor sun protection.', 'accessories', 12.12, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image455.webp', 50, '', false, false, 'solar_fan_hat', 'White/8to16 Hours');

-- High-grade Aurora Manicure Fake Nail Tip (nails, +$12)
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('08321fa0-cf20-47a6-888e-27e24f23767b', 'High-grade Aurora Manicure Fake Nail Tip - DS29 Aurora/Yellow Jelly Glue', 'High-grade aurora-effect fake nail tips with jelly glue attachment. DS29 aurora shimmer finish for a dazzling manicure look.', 'nails', 14.21, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image456.webp', 50, '', false, false, 'aurora_fake_nail_tip', 'DS29 Aurora/Yellow Jelly Glue');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('4e8fcfab-84ad-4987-86b3-20cca7e75fdd', 'High-grade Aurora Manicure Fake Nail Tip - DS29 Aurora/Black Jelly Glue', 'High-grade aurora-effect fake nail tips with jelly glue attachment. DS29 aurora shimmer finish for a dazzling manicure look.', 'nails', 14.21, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image456.webp', 50, '', false, false, 'aurora_fake_nail_tip', 'DS29 Aurora/Black Jelly Glue');

-- Mesh Cold Boot Martin Boots (accessories, +$3)
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('5bcc409c-2787-4bc9-a87a-f5ffee93917d', 'Mesh Cold Boot - black/36', 'Stylish mesh Martin boots with thin heels and pointed toes. Breathable mesh design keeps feet cool while looking chic.', 'accessories', 22.67, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image457.webp', 50, '', false, false, 'mesh_cold_boot', 'black/36');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('67386135-f2da-440b-84d2-59ed43c75100', 'Mesh Cold Boot - black/37', 'Stylish mesh Martin boots with thin heels and pointed toes. Breathable mesh design keeps feet cool while looking chic.', 'accessories', 22.67, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image457.webp', 50, '', false, false, 'mesh_cold_boot', 'black/37');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('6df7f78d-59b8-4352-bd10-a1761b4c13fa', 'Mesh Cold Boot - black/38', 'Stylish mesh Martin boots with thin heels and pointed toes. Breathable mesh design keeps feet cool while looking chic.', 'accessories', 22.67, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image457.webp', 50, '', false, false, 'mesh_cold_boot', 'black/38');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('d56d5bf9-5fbb-4ce2-9f81-b47d1550ff44', 'Mesh Cold Boot - black/39', 'Stylish mesh Martin boots with thin heels and pointed toes. Breathable mesh design keeps feet cool while looking chic.', 'accessories', 22.67, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image457.webp', 50, '', false, false, 'mesh_cold_boot', 'black/39');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('9f29e643-6ec9-4bf0-a30a-2c25ec0a5253', 'Mesh Cold Boot - black/40', 'Stylish mesh Martin boots with thin heels and pointed toes. Breathable mesh design keeps feet cool while looking chic.', 'accessories', 22.67, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image457.webp', 50, '', false, false, 'mesh_cold_boot', 'black/40');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('ac3426fc-f761-49fd-bac3-90dd0558fc16', 'Mesh Cold Boot - black/41', 'Stylish mesh Martin boots with thin heels and pointed toes. Breathable mesh design keeps feet cool while looking chic.', 'accessories', 22.67, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image457.webp', 50, '', false, false, 'mesh_cold_boot', 'black/41');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('e59bab8f-873a-40aa-85af-cd293af5e2e7', 'Mesh Cold Boot - black/42', 'Stylish mesh Martin boots with thin heels and pointed toes. Breathable mesh design keeps feet cool while looking chic.', 'accessories', 22.67, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image457.webp', 50, '', false, false, 'mesh_cold_boot', 'black/42');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('11819bb1-e432-4034-9c93-232627cad0cb', 'Mesh Cold Boot - black/35', 'Stylish mesh Martin boots with thin heels and pointed toes. Breathable mesh design keeps feet cool while looking chic.', 'accessories', 22.67, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image457.webp', 50, '', false, false, 'mesh_cold_boot', 'black/35');

-- EMS Thermal Neck Lifting Massager (accessories, +$3)
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('49c589f0-19f2-494f-980c-64f8f7bdb662', 'EMS Thermal Neck Lifting Massager - White', 'EMS thermal neck lifting massager with microcurrent technology. Tightens and rejuvenates neck skin while reducing wrinkles.', 'accessories', 12.69, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image458.webp', 50, '', false, false, 'ems_neck_lifting', 'White');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('ca44a57e-d6fc-483e-8d90-8989412af105', 'EMS Thermal Neck Lifting Massager - Black Silver', 'EMS thermal neck lifting massager with microcurrent technology. Tightens and rejuvenates neck skin while reducing wrinkles.', 'accessories', 12.95, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image458.webp', 50, '', false, false, 'ems_neck_lifting', 'Black Silver');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('a3a8df5e-bd23-4320-96a7-076187bdf5c2', 'EMS Thermal Neck Lifting Massager - Cable', 'EMS thermal neck lifting massager with microcurrent technology. Tightens and rejuvenates neck skin while reducing wrinkles.', 'accessories', 3.33, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image458.webp', 50, '', false, false, 'ems_neck_lifting', 'Cable');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('57561a95-ce85-4031-9e9b-7f775a6f3438', 'EMS Thermal Neck Lifting Massager - Set', 'EMS thermal neck lifting massager with microcurrent technology. Tightens and rejuvenates neck skin while reducing wrinkles.', 'accessories', 12.86, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image458.webp', 50, '', false, false, 'ems_neck_lifting', 'Set');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('0e58b8f4-6885-40b6-8509-ee26bb74f28e', 'EMS Thermal Neck Lifting Massager - White Pink', 'EMS thermal neck lifting massager with microcurrent technology. Tightens and rejuvenates neck skin while reducing wrinkles.', 'accessories', 14.77, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image458.webp', 50, '', false, false, 'ems_neck_lifting', 'White Pink');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('0d73cc67-bce4-4b21-a545-accfb5e778d6', 'EMS Thermal Neck Lifting Massager - Black Silver set', 'EMS thermal neck lifting massager with microcurrent technology. Tightens and rejuvenates neck skin while reducing wrinkles.', 'accessories', 15.03, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image458.webp', 50, '', false, false, 'ems_neck_lifting', 'Black Silver set');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('7bd1c426-37f7-47a8-bee3-d204c5f070b9', 'EMS Thermal Neck Lifting Massager - Pink seven color lamp', 'EMS thermal neck lifting massager with microcurrent technology. Tightens and rejuvenates neck skin while reducing wrinkles.', 'accessories', 7.19, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image458.webp', 50, '', false, false, 'ems_neck_lifting', 'Pink seven color lamp');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('76ed9dcf-2f31-4e5a-991b-1f781bc53002', 'EMS Thermal Neck Lifting Massager - Black Silver set 2', 'EMS thermal neck lifting massager with microcurrent technology. Tightens and rejuvenates neck skin while reducing wrinkles.', 'accessories', 13.28, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image458.webp', 50, '', false, false, 'ems_neck_lifting', 'Black Silver set 2');
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('66440ed2-d4e2-4bec-bfe3-4288ff06e1a3', 'EMS Thermal Neck Lifting Massager - White set', 'EMS thermal neck lifting massager with microcurrent technology. Tightens and rejuvenates neck skin while reducing wrinkles.', 'accessories', 15.79, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image458.webp', 50, '', false, false, 'ems_neck_lifting', 'White set');

-- White French Classic Fake Nails (nails, +$12)
INSERT INTO products (id, name, description, category, price, image_url, inventory, badge, is_featured, is_slider, variant_group, style_label) VALUES
  ('0d2c54f0-c2a7-4add-b622-3699e9004995', 'White French Classic Fake Nails - XSS288', 'White French classic all-match detachable fake nails. Gentle, versatile design for a timeless and elegant nail look.', 'nails', 12.86, 'https://gfhnwydldnvtvquagzav.supabase.co/storage/v1/object/public/product-images/cj/f1_image459.webp', 50, '', false, false, NULL, 'XSS288');
