name: Deploy to Cloudflare Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Frontend to Cloudflare Pages
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: b0c5322365b665c885bf3afd3d0a25cd
          projectName: clcbeauties
          directory: .
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: main
